# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          myimage1
- stage: Push
  displayName: Push image
  jobs: 
  - job: Push
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Push image
        inputs:
           azureSubscription: Dockerhub connection rahamat
           repository: lttspoc
           command: push
           tags: |
             myimage1
               
