# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'rahmath/lttspoc:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: Dockerhubconnectionrahamat
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Docker Hub'
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        imageName: '$(ImageName)'
        tags: |
          $(tag)
- stage: Push
  displayName: Push image
  jobs: 
  - job: Push
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: Docker@2
        displayName: Push image
        inputs:
           containerRegistry: Dockerhubconnectionrahamat
           containerregistrytype: 'Container Registry'
           dockerRegistryEndpoint: 'Docker Hub'
           imageName: '$(ImageName)'
           repository: lttspoc
           command: push
           tags: |
              $(tag)

               
