# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'rahmath/lttspoc:$(Build.BuildId)'

stages:
- stage: Build_and_Push
  displayName: 'Build and Push image'
  jobs: 
  - job: buildAndPush
    displayName: Push
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        containerRegistry: rahamth-acr
        repository: raham3144/lttspoc # username/contosoRepository for DockerHub
        tags: |
           rahmat
